name: Bugs Form Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --tag datacom-demo
      - name: Run tests
        run: docker run --name datacom-demo-container datacom-demo
      - name: Copy test results from container
        run: docker cp datacom-demo-container:/app/test-results ./test-results
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-traces
          path: test-results/
